# Generated by Django 5.1.4 on 2024-12-22 19:28

import django.db.models.deletion
import multiselectfield.db.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_shop', '0002_actor_actor_name_en_actor_actor_name_ru_actor_bio_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moments',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_moments', to='movie_shop.movie'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='actor',
            field=models.ManyToManyField(related_name='actors', to='movie_shop.actor'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='country',
            field=models.ManyToManyField(related_name='movies', to='movie_shop.country'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='director',
            field=models.ManyToManyField(related_name='directors', to='movie_shop.director'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.ManyToManyField(related_name='genres', to='movie_shop.genre'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='types',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('144p', '144p'), ('360p', '360p'), ('480p', '480p'), ('720p', '720p'), ('1080p', '1080p')], max_length=160),
        ),
        migrations.AlterField(
            model_name='movielanguages',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_languages', to='movie_shop.movie'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='movie_shop.movie'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
    ]
